### ISSUE TITLE
771_Jewels_and_Stones

### ISSUE THREAD

**Issue by k4733294** [housemeow/Leetcode#1]
hi kelly master,
How do you do of  this question?
Please promote your thinking. 

Thank you 
Madeon Liu

**Comment by housemeow** [comment]
> hi kelly master,
> How do you do of this question?
> Please promote your thinking.
> 
> Thank you
> Madeon Liu

J字串的字元是一顆顆的寶石
S字串的字元是一顆顆的石頭
要比較有「幾顆石頭」是寶石
Input: J = "aA", S = "aAAbbbb"
Output: 3

初步構想是先把寶石建成map，這樣搜尋就會很快
然後直接for一圈石頭，找找看map有沒有，有就+1顆
應該可以

**Comment by housemeow** [comment]
講錯了這邊不應該用map，應該用set就可以了

**Comment by k4733294** [comment]
Hi kelly,
thank you your reply
that's really  open my mind.
I'll keep going on other question

Thank you
