### ISSUE TITLE
5_Longest Palindromic Substring/Dennaolan.cpp

### ISSUE THREAD

**Issue by Dennaolan** [housemeow/Leetcode#4]
Hi everyone, these are some optimal question for you.
In the two version of Question 5's  solutions have the optimal problem that can't attempt to pass.
Please optimal both source code and try not to change the architecture.

Best regards

**Comment by housemeow** [comment]
你的解法是 i ~ j的距離取中位，在判斷i ~ 中  reverse(中~j)是否相等嗎？

**Comment by Dennaolan** [comment]
> 你的解法是 i ~ j的距離取中位，在判斷i ~ 中 reverse(中~j)是否相等嗎？
Yes

**Comment by housemeow** [comment]
對稱的特色是，如果有遇到重複的字元，才需要做比較。你可以先從for迴圈中找到有重複的字元，再做比較字串

**Comment by housemeow** [comment]
建表概念是這樣：
char appearIndex[256]
appearIndex.setAll(-1)
if (appearIndex['A'] != -1)
   'A' is appearBefore

**Comment by Dennaolan** [comment]
加了兩個條件還是Timeout，試問單兵該如何處置？

**Comment by housemeow** [comment]
可以再試試看，只比較長度比目前最大長度還大的字串

**Comment by Dennaolan** [comment]
> 可以再試試看，只比較長度比目前最大長度還大的字串

我有做喔，註解有寫

**Comment by k4733294** [comment]
我是用訊框的概念處理  ex: abba  可以看成 ws:2 ab bb ba ws:3  abb  bba ws:4  abba 1.如果在windowsize找到任何可倒述的結果 則跳出該迴圈 window size 直接進一個寬度 2. 起始位置的加速可以store 上一個windowsize reverse success 的position 從該處開始

你的方式是iteration positon with  looping all windows size  這個部分要如何整合 可以再想一下

**Comment by Dennaolan** [comment]
後來用 @housemeow 的從一個軸開始往兩側找的方式總算是通過了
感謝 @housemeow 的協助
